In [1]:
import numpy as np
import pandas as pd
import requests

In [21]:
def get_ma_data(variable):
  api_base = "https://api.census.gov/data/2015/acs5/profile?for=zip%20code%20tabulation%20area:*&get=NAME,"
  return requests.get(api_base + variable).json()

In [22]:
ma_zip_codes = pd.read_csv("school_addresses.csv", encoding = "ISO-8859-1", converters={'Zip Code': str})
zip_list = list(set(ma_zip_codes['Zip Code'].tolist()))

In [23]:
perc_white = get_ma_data("DP05_0032PE")

In [24]:
df = []

for i in perc_white:
    if i[2] in zip_list:
        df.append(i)

In [25]:
perc_white_df = pd.DataFrame(df, columns = ["Name", "Zip Perc White", "Zip Code"])

In [26]:
median_income = get_ma_data("DP03_0062E")

In [27]:
df = []

for i in median_income:
    if i[2] in zip_list:
        df.append(i)

In [28]:
median_income_df = pd.DataFrame(df, columns = ["Name", "Median Income", "Zip Code"])

In [29]:
median_income_df

            Name Median Income Zip Code
0    ZCTA5 01001         60161    01001
1    ZCTA5 01002         50540    01002
2    ZCTA5 01005         68786    01005
3    ZCTA5 01007         76881    01007
4    ZCTA5 01010         87961    01010
5    ZCTA5 01011         68000    01011
6    ZCTA5 01012         57019    01012
7    ZCTA5 01013         40774    01013
8    ZCTA5 01020         55665    01020
9    ZCTA5 01022         51500    01022
10   ZCTA5 01027         58324    01027
11   ZCTA5 01028         81655    01028
12   ZCTA5 01030         63026    01030
13   ZCTA5 01031         39750    01031
14   ZCTA5 01033         87222    01033
15   ZCTA5 01035         65625    01035
16   ZCTA5 01036         81018    01036
17   ZCTA5 01038         66607    01038
18   ZCTA5 01040         36608    01040
19   ZCTA5 01050         62446    01050
20   ZCTA5 01053         59948    01053
21   ZCTA5 01054         83333    01054
22   ZCTA5 01056         63548    01056
23   ZCTA5 01057         68156    01057
24   ZCTA5 01060         51651    01060
25   ZCTA5 01062         67939    01062
26   ZCTA5 01068         80313    01068
27   ZCTA5 01069         54141    01069
28   ZCTA5 01071         73611    01071
29   ZCTA5 01072         69250    01072
..           ...           ...      ...
398  ZCTA5 02715         77292    02715
399  ZCTA5 02717         81061    02717
400  ZCTA5 02718         86343    02718
401  ZCTA5 02719         61274    02719
402  ZCTA5 02720         44397    02720
403  ZCTA5 02721         29684    02721
404  ZCTA5 02723         32275    02723
405  ZCTA5 02724         30688    02724
406  ZCTA5 02726         72585    02726
407  ZCTA5 02738         76503    02738
408  ZCTA5 02739         86659    02739
409  ZCTA5 02740         35887    02740
410  ZCTA5 02743         67263    02743
411  ZCTA5 02744         31709    02744
412  ZCTA5 02745         51328    02745
413  ZCTA5 02746         26705    02746
414  ZCTA5 02747         70919    02747
415  ZCTA5 02748         64625    02748
416  ZCTA5 02760         80957    02760
417  ZCTA5 02762         91009    02762
418  ZCTA5 02764         78870    02764
419  ZCTA5 02766         91438    02766
420  ZCTA5 02767         83125    02767
421  ZCTA5 02769         88868    02769
422  ZCTA5 02770         97157    02770
423  ZCTA5 02771         76826    02771
424  ZCTA5 02777         73310    02777
425  ZCTA5 02779         86288    02779
426  ZCTA5 02780         50653    02780
427  ZCTA5 02790         79697    02790

[428 rows x 3 columns]

In [30]:
perc_poverty_kids = get_ma_data("DP03_0120PE")

In [31]:
df = []

for i in perc_poverty_kids:
    if i[2] in zip_list:
        df.append(i)

percent_poverty_kids_df = pd.DataFrame(df, columns = ["Name", "Percent Poverty", "Zip Code"])

In [32]:
hs_grad = get_ma_data("DP02_0066PE")

In [33]:
df = []

for i in hs_grad:
    if i[2] in zip_list:
        df.append(i)

In [34]:
hs_grad_df = pd.DataFrame(df, columns = ["Name", "% HS Graduates", "Zip Code"])

In [35]:
college_grad = get_ma_data("DP02_0067PE")

In [36]:
df = []

for i in college_grad:
    if i[2] in zip_list:
        df.append(i)

In [37]:
college_grad_df = pd.DataFrame(df, columns = ["Name", "% College Graduates", "Zip Code"])

In [38]:
college_grad_df

            Name % College Graduates Zip Code
0    ZCTA5 01001                28.0    01001
1    ZCTA5 01002                68.0    01002
2    ZCTA5 01005                24.0    01005
3    ZCTA5 01007                42.0    01007
4    ZCTA5 01010                41.6    01010
5    ZCTA5 01011                17.8    01011
6    ZCTA5 01012                41.0    01012
7    ZCTA5 01013                16.0    01013
8    ZCTA5 01020                17.4    01020
9    ZCTA5 01022                27.5    01022
10   ZCTA5 01027                33.4    01027
11   ZCTA5 01028                41.2    01028
12   ZCTA5 01030                29.1    01030
13   ZCTA5 01031                20.7    01031
14   ZCTA5 01033                34.1    01033
15   ZCTA5 01035                46.4    01035
16   ZCTA5 01036                37.9    01036
17   ZCTA5 01038                38.6    01038
18   ZCTA5 01040                23.4    01040
19   ZCTA5 01050                18.5    01050
20   ZCTA5 01053                41.1    01053
21   ZCTA5 01054                62.5    01054
22   ZCTA5 01056                20.8    01056
23   ZCTA5 01057                27.7    01057
24   ZCTA5 01060                60.3    01060
25   ZCTA5 01062                56.9    01062
26   ZCTA5 01068                37.5    01068
27   ZCTA5 01069                24.5    01069
28   ZCTA5 01071                29.9    01071
29   ZCTA5 01072                62.9    01072
..           ...                 ...      ...
398  ZCTA5 02715                33.2    02715
399  ZCTA5 02717                22.5    02717
400  ZCTA5 02718                25.1    02718
401  ZCTA5 02719                26.0    02719
402  ZCTA5 02720                20.0    02720
403  ZCTA5 02721                 9.6    02721
404  ZCTA5 02723                 9.9    02723
405  ZCTA5 02724                11.1    02724
406  ZCTA5 02726                26.8    02726
407  ZCTA5 02738                50.3    02738
408  ZCTA5 02739                47.9    02739
409  ZCTA5 02740                17.9    02740
410  ZCTA5 02743                23.1    02743
411  ZCTA5 02744                14.5    02744
412  ZCTA5 02745                17.9    02745
413  ZCTA5 02746                 7.6    02746
414  ZCTA5 02747                25.5    02747
415  ZCTA5 02748                34.7    02748
416  ZCTA5 02760                40.4    02760
417  ZCTA5 02762                42.4    02762
418  ZCTA5 02764                24.1    02764
419  ZCTA5 02766                36.6    02766
420  ZCTA5 02767                35.1    02767
421  ZCTA5 02769                37.4    02769
422  ZCTA5 02770                40.7    02770
423  ZCTA5 02771                32.9    02771
424  ZCTA5 02777                23.8    02777
425  ZCTA5 02779                28.0    02779
426  ZCTA5 02780                17.9    02780
427  ZCTA5 02790                30.2    02790

[428 rows x 3 columns]

In [39]:
acs_all = pd.merge(median_income_df, percent_poverty_kids_df)
acs_all = pd.merge(acs_all, hs_grad_df)
acs_all = pd.merge(acs_all, college_grad_df)
acs_all = pd.merge(acs_all, perc_white_df)

In [41]:
acs_all.to_csv("acs_indicators_by_zip.csv")